run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - goconst
    - gocyclo
    - godot
    - gofmt
    - govet
    - lll
    - misspell
    - nilerr
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - typecheck
    - unconvert
    - unparam
    - unused
    - unused
