version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
    - unconvert
    - unparam
    - gocyclo
    - prealloc
    - goconst
    - godot
    - gocognit
    - dupl
